[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ME-405-Term-Project"
authors = [{name = "Andrew Jones", email = "ajone168@calpoly.edu"}]
dynamic = ["version", "description"]
